### ISSUE TITLE
Allow reading `Credentials` in `LoginClient` API

### ISSUE THREAD

**Issue by lukaszgarstecki** [leancodepl/flutter_corelibrary#109]
Currently there is only a method `onCredentialsChanged` that gives you new `Credentials?` object you base .

I have a case where I'd need read to access the `accessToken` and perform some action outside `LoginClient` with it. Currently there is no way to do so.

**Comment by Albert221** [comment]
You can access the current access token indirectly by `read()`ing from `CredentialsStorage`.

We may replace the `onCredentialsChanged` stream with a behavior subject, because if we already give access to the raw OAuth credentials on their update, we may as well make it possible to synchronically retrieve them if needed.
