### ISSUE TITLE
Evaluate new lints from Dart 3.0

### ISSUE THREAD

**Issue by shilangyu** [leancodepl/flutter_corelibrary#99]
- new: [`implicit_reopen`](https://dart-lang.github.io/linter/lints/implicit_reopen.html)
- new: [`unnecessary_breaks`](https://dart-lang.github.io/linter/lints/unnecessary_breaks.html)
- new: [`type_literal_in_constant_pattern`](https://dart-lang.github.io/linter/lints/type_literal_in_constant_pattern.html)
- new: [`invalid_case_patterns`](https://dart-lang.github.io/linter/lints/invalid_case_patterns.html)
- new: [`deprecated_member_use_from_same_package`](https://dart-lang.github.io/linter/lints/deprecated_member_use_from_same_package.html)
- removed: [`enable_null_safety`](https://dart-lang.github.io/linter/lints/enable_null_safety.html)
- updated (to track static elements): [`unreachable_from_main`](https://dart-lang.github.io/linter/lints/unreachable_from_main.html)

**Comment by shilangyu** [comment]
Not much to discuss about [enable_null_safety](https://dart-lang.github.io/linter/lints/enable_null_safety.html), this one was just removed so we have to remove it.

**Comment by bartekpacia** [comment]
I don't like `implicit_reopen`.

I think it'll result in every class being `final`. It doesn't matter that much in apps (where we control all the code), but for packages, it's bad, IMHO.

I'm fond of Python's "we are all consenting adults here" approach (meaning you can access all classes, functions, etc. – i.e _nothing is private_ – but you have to know what you're doing). Too many times I had to find hacks or copy code because the functionality I needed was private.

BTW, why is it called `implicit_reopen`, not `implicit_open`?
